/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "sys_f446xx.h"
#include "bsp.h"

void Gpio_myInit(void);
void i2c_myInit(void);

int main(void)
{
	Gpio_myInit(); 	/* Initializing I2C GPIO pins (alt. function) */
	i2c_myInit();	/* Initializing I2C */

    while(1)
    {
		
    }
}

void Gpio_myInit(void)
{
	/* Pin 13 of Port C is connected to On-Board User Button */
	(void)Gpio_PortInit(portc);
	(void)Gpio_PinMode(portc, pin13, input);

	/****** I2C1 Related Configuration ******/
	Gpio_PortInit(portb);

	/* Pins used for I2C1 */
	Gpio_PinMode(portb, pin8, alternate);
	Gpio_PinMode(portb, pin9, alternate);

	/* Alternate Function 4 - I2C related */
	Gpio_ConfigAltFnc(portb, pin8, altFun4); /* SCL */
	Gpio_ConfigAltFnc(portb, pin9, altFun4); /* SDA */ 

	/* According to I2C spec, pins should be open-drain
	and pulled to high through resistors (either internal
	or external) */
	Gpio_OutputTypeCfg(portb, pin8, openDrain);
	Gpio_OutputTypeCfg(portb, pin9, openDrain);

	/* Making use of internal pull-up resistors for now */
	Gpio_PullMode(portb, pin8, pullUp);
	Gpio_PullMode(portb, pin9, pullUp);
	
	/****** End of I2C1 Related Configuration ******/
	
}

void i2c_myInit(void)
{

}
