/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"

int main(void)
{
	Gpio_PortInit(porta);
	Gpio_PinMode(porta, 5, output);
	Gpio_SetPinState(porta, 5, high);
	Gpio_SetPinState(porta, 5, low);

    /* Loop forever */
	while(1)
	{
		uint32_t index = 0;
		for(index = 0; index < 100000; index++);
		Gpio_SetPinState(porta, 5, low);
		for(index = 0; index < 100000; index++);
		Gpio_SetPinState(porta, 5, high);
	}
}
