/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"

int main(void)
{
	/* Pin 5 of Port A is connected to On-Board Green LED */
	/* Pin 13 of Port C is connected to On-Board User Button */
    Gpio_PortInit(porta);
    Gpio_PortInit(portc);

    Gpio_PinMode(porta, pin5, output);
    Gpio_PinMode(portc, pin13, input);

    while(1)
    {
    	Gpio_SetPinState(porta, pin5, HIGH);

    	while(Gpio_GetPinStateVal(portc, pin13) == LOW)
    	{
    		Gpio_SetPinState(porta, pin5, LOW);
    	}
    }
}
