/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "sys_f446xx.h"
#include "bsp.h"

void Gpio_myInit(void);
void Spi_myInit(void);

int main(void)
{
	uint8_t rxData[12];
	Gpio_myInit(); 	/* Initializing SPI GPIO pins (alt. function) */
	Spi_myInit();	/* Initializing SPI (slave mode) */

    while(1)
    {
		Spi_PeripheralEnable(SPI_1);	/* Enabling SPI1 Peripheral. */

		uint8_t i;
		/* First, master sends the number of elements 
		that slave should receive */
		uint8_t rxDataLen = Spi_ReadData(SPI1);

		for (i = 0; i < rxDataLen; i++)
		{
			/* Receive data from DR (blocking call).
			This function will wait until it receives
			clock from master. */
			rxData[i] = Spi_ReadData(SPI1);
		}

		/* We need to terminate String with New line. */
		rxData[i] = '\n';
		while (1u == Spi_ReadBSYFlag(SPI_1));
		/* Print it through Software-Trace-Monitoring (STM cell) */
		for (i = 0; i < rxDataLen; i++)
		{
			printf("rx[%d] = %c\n", i, rxData[i]);
		}
	
		Spi_PeripheralDisable(SPI_1);
    }
}

void Gpio_myInit(void)
{
	/* Pin 13 of Port C is connected to On-Board User Button */
	(void)Gpio_PortInit(portc);
	(void)Gpio_PinMode(portc, pin13, input);

	/* SPI1 Related Configuration */
	Gpio_PortInit(porta);
	Gpio_PinMode(porta, pin4, alternate);
	Gpio_PinMode(porta, pin5, alternate);
	Gpio_PinMode(porta, pin6, alternate);
	Gpio_PinMode(porta, pin7, alternate);

	Gpio_ConfigAltFnc(porta, pin4, altFun5);
	Gpio_ConfigAltFnc(porta, pin5, altFun5);
	Gpio_ConfigAltFnc(porta, pin6, altFun5);
	Gpio_ConfigAltFnc(porta, pin7, altFun5);

	Gpio_OutputTypeCfg(porta, pin4, pushPull);
	Gpio_OutputTypeCfg(porta, pin5, pushPull);
	Gpio_OutputTypeCfg(porta, pin6, pushPull);
	Gpio_OutputTypeCfg(porta, pin7, pushPull);

	Gpio_PullMode(porta, pin4, none);
	Gpio_PullMode(porta, pin5, none);
	Gpio_PullMode(porta, pin6, none);
	Gpio_PullMode(porta, pin7, none);

	Gpio_OutputSpeed(porta, pin4, highSpeed);
	Gpio_OutputSpeed(porta, pin5, highSpeed);
	Gpio_OutputSpeed(porta, pin6, highSpeed);
	Gpio_OutputSpeed(porta, pin7, highSpeed);
}

void Spi_myInit(void)
{
	SPI1_ENABLE();
	Spi_Config1Type spi1cfg1;
	spi1cfg1.Bytes = 0;
	spi1cfg1.Fields.BIDIMODE = twoLineUni;
	spi1cfg1.Fields.CPHA = firstEdge;
	spi1cfg1.Fields.CPOL = clkPolLowIdle;
	spi1cfg1.Fields.DFF = oneByte;
	spi1cfg1.Fields.MSTR = spiSlave;
	spi1cfg1.Fields.SSM = swMgtDisabled;

	Spi_Config_CR1(SPI_1, spi1cfg1.Bytes);
}
