/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

uint8_t volatile g_button_pressed = 0;
uint8_t g_button_press_counter = 0;

uint32_t volatile *pRCC_ControlReg_AHB1 = (uint32_t*)0x40023830;
uint32_t volatile *pRCC_ControlReg_APB2 = (uint32_t*)0x40023844;

uint32_t volatile *pEXTI_MaskReg = (uint32_t*)0x40013C00;
uint32_t volatile *pEXTI_RisingTriggerReg = (uint32_t*)0x40013C08;
uint32_t volatile *pEXTI_PendingReg = (uint32_t*)0x40013C14;

uint32_t volatile *pNVIC_ISER1 = (uint32_t*)0xE000E104;

uint32_t volatile *pSYSCFG_EXTICR4 = (uint32_t*)0x40013814;

void button_init(void);
void delay();


int main(void)
{
	printf("Initializing the program\n");

    button_init();

    while(1)
    {
       *pEXTI_MaskReg &= ~(1 << 13);

        if(g_button_pressed)
        {
            delay();
            g_button_press_counter++;
            printf("\nButton is pressed %u times!", g_button_press_counter);
            g_button_pressed = 0;
        }

        *pEXTI_MaskReg |= (1 << 13);
    }
}

void button_init(void)
{
    /* GPIOC peripheral clock enabled for Port C */
    *pRCC_ControlReg_AHB1 |= (1 << 2);

    /* Set 14th bit to enable clock on APB2 */
    *pRCC_ControlReg_APB2 |= (1 << 14);

    /* Setting port C for EXTI line 15_10 */
    *pSYSCFG_EXTICR4 &= ~(0x2 << 4);
    *pSYSCFG_EXTICR4 |= (1 << 5);

    /* Rising trigger disabled */
    *pEXTI_RisingTriggerReg |= (1 << 13);

    /* Mask set up */
    *pEXTI_MaskReg |= (1 << 13);

    /* IRQ Configuration */
    *pNVIC_ISER1 |= (1 << (40 % 32));
}

void delay(void)
{
    for(uint32_t i = 0; i < 200000; i++);
}

void EXTI15_10_IRQHandler(void)
{
    if(*pEXTI_PendingReg & (1 << 13))
    {
        /* Clear pin */
        *pEXTI_PendingReg |= (1 << 13);
    }
    g_button_pressed = 1;
}
