/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpio.h"

int main(void)
{

	RCC_AHB1ENR->GPIOAEN = TRUE;
	RCC_AHB1ENR->GPIOCEN = TRUE;

	GPIOA_MODER->pin5 = output;
	GPIOC_MODER->pin13 = input;

    /* Loop forever */
	while(1)
	{
		GPIOA_ODR->pin5 = HIGH;
		while(GPIOC_IDR->pin13 == LOW)
		{
			GPIOA_ODR->pin5 = LOW;
		}
	}
}
