/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include<stdio.h>
#include "other.h"

extern void initialise_monitor_handles(void);

const uint8_t constant_data = 200;
uint32_t uninitialized_data;
uint16_t initialized_data = 150;

int main(void)
{
    Gpio_Init();
	initialise_monitor_handles();
	printf("Testing\n");
	uint8_t flag = 0;

    while (1)
    {
		/* Input pin is configured as active-low */
		gpioState inputButtonSt = Gpio_ReadPinState();

		if (GPIO_HIGH == inputButtonSt)
		{
			Gpio_SetPinState(GPIO_LOW);
			flag = 1;
		}
		else
		{
			Gpio_SetPinState(GPIO_HIGH);
			if (flag == 1)
			{
				printf("Pressing\n");
				flag = 0;
			}
			
		}
    }

    return 0;
}
