/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "sys_f446xx.h"

int main(void)
{
	char user_data[] = "hello world";
	Gpio_Init(); 	/* Initializing SPI GPIO pins (alt. function) */
	Spi_Init();		/* Initializing SPI. */

	Spi_SetSSI(SPI_1);	/* Activate Slave Selection through SW. */

	Spi_PeripheralEnable(SPI_1);	/* Enabling SPI1 Peripheral. */

	/* Send SPI Data, blocking code */
	Spi_SendData(SPI1, (uint8_t*)user_data, strlen(user_data));
	/* Check following operation. BUSY flag doesn't seem to be set */
	while (!(SPI_SR_BSY == (SPI1->SR & (uint32_t)SPI_SR_BSY)));

	/* Loop forever */
	while(1)
	{
	}
}

