/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * This SW contains the implementation of interfacing 4x4 keypad. Every time
 * a key is pressed, it is printed out on Serial Wire Viewer (SWV) console
 * */

#include <stdint.h>
#include "gpio.h"
#include "stdio.h"

#define DELAY 200000u

#define uint32 uint32_t

void delay(uint32 delayValue)
{
	for(volatile uint32 i = 0; i < delayValue; i++);
}

/* Pin 5 of Port A is connected to On-Board Green LED */
/* Pin 13 of Port C is connected to On-Board User Button */

int main(void)
{
	printf("Starting...\n");

	Gpio_PortInit(portc);
	Gpio_PortInit(porta);

	/* We use these pins as output to detect if a key is pressed or not. */
	Gpio_PinMode(porta, pin6, output);
	Gpio_PinMode(porta, pin7, output);
	Gpio_PinMode(porta, pin8, output);
	Gpio_PinMode(porta, pin9, output);

	Gpio_PinMode(portc, pin9, input);
	Gpio_PinMode(portc, pin10, input);
	Gpio_PinMode(portc, pin11, input);
	Gpio_PinMode(portc, pin12, input);

	Gpio_PinMode(portc, pin13, input);

	Gpio_PullMode(portc, pin9, pullup);
	Gpio_PullMode(portc, pin10, pullup);
	Gpio_PullMode(portc, pin11, pullup);
	Gpio_PullMode(portc, pin12, pullup);

    /* Loop forever */
	while(1)
	{
		pinState pinLevel;
		Gpio_SetPinState(porta, pin6, HIGH);
		Gpio_SetPinState(porta, pin7, HIGH);
		Gpio_SetPinState(porta, pin8, HIGH);
		Gpio_SetPinState(porta, pin9, HIGH);

		/* ********** First row ********** */
		Gpio_SetPinState(porta, pin6, LOW);
		Gpio_GetPinStateRef(portc, pin9, &pinLevel);
		if(pinLevel == LOW)
		{
			delay(DELAY);
			printf("1\n");
		}

		Gpio_GetPinStateRef(portc, pin10, &pinLevel);
		if(pinLevel == LOW)
		{
			delay(DELAY);
			printf("2\n");
		}

		Gpio_GetPinStateRef(portc, pin11, &pinLevel);
		if(pinLevel == LOW)
		{
			delay(DELAY);
			printf("3\n");
		}

		Gpio_GetPinStateRef(portc, pin12, &pinLevel);
		if(pinLevel == LOW)
		{
			delay(DELAY);
			printf("A\n");
		}
		Gpio_SetPinState(porta, pin6, HIGH);
		/* ********** End of first row ********** */

		/* ********** Second row ********** */
		Gpio_SetPinState(porta, pin7, LOW);
		Gpio_GetPinStateRef(portc, pin9, &pinLevel);
		if(pinLevel == LOW)
		{
			delay(DELAY);
			printf("4\n");
		}

		Gpio_GetPinStateRef(portc, pin10, &pinLevel);
		if(pinLevel == LOW)
		{
			delay(DELAY);
			printf("5\n");
		}

		Gpio_GetPinStateRef(portc, pin11, &pinLevel);
		if(pinLevel == LOW)
		{
			delay(DELAY);
			printf("6\n");
		}

		Gpio_GetPinStateRef(portc, pin12, &pinLevel);
		if(pinLevel == LOW)
		{
			delay(DELAY);
			printf("B\n");
		}
		Gpio_SetPinState(porta, pin7, HIGH);
		/* ********** End of second row ********** */

		/* ********** Third row ********** */
		Gpio_SetPinState(porta, pin8, LOW);
		Gpio_GetPinStateRef(portc, pin9, &pinLevel);
		if(pinLevel == LOW)
		{
			delay(DELAY);
			printf("7\n");
		}

		Gpio_GetPinStateRef(portc, pin10, &pinLevel);
		if(pinLevel == LOW)
		{
			delay(DELAY);
			printf("8\n");
		}

		Gpio_GetPinStateRef(portc, pin11, &pinLevel);
		if(pinLevel == LOW)
		{
			delay(DELAY);
			printf("9\n");
		}

		Gpio_GetPinStateRef(portc, pin12, &pinLevel);
		if(pinLevel == LOW)
		{
			delay(DELAY);
			printf("C\n");
		}
		Gpio_SetPinState(porta, pin8, HIGH);
		/* ********** End of third row ********** */

		/* ********** Forth row ********** */
		Gpio_SetPinState(porta, pin9, LOW);
		Gpio_GetPinStateRef(portc, pin9, &pinLevel);
		if(pinLevel == LOW)
		{
			delay(DELAY);
			printf("*\n");
		}

		Gpio_GetPinStateRef(portc, pin10, &pinLevel);
		if(pinLevel == LOW)
		{
			delay(DELAY);
			printf("0\n");
		}

		Gpio_GetPinStateRef(portc, pin11, &pinLevel);
		if(pinLevel == LOW)
		{
			delay(DELAY);
			printf("#\n");
		}

		Gpio_GetPinStateRef(portc, pin12, &pinLevel);
		if(pinLevel == LOW)
		{
			delay(DELAY);
			printf("D\n");
		}
		Gpio_SetPinState(porta, pin9, HIGH);
		/* ********** End of forth row ********** */
	} /* End of while loop */
}
