/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "sys_f446xx.h"
#include "bsp.h"

int main(void)
{
	char user_data[] = "hello world";
	Gpio_Init(); 	/* Initializing SPI GPIO pins (alt. function) */
	Spi_Init();		/* Initializing SPI. */

	/* NSS Output Enable. NSS pin is driven by HW. NSS pin is pulled to low
	as soon as SPI is enabled in master mode (SPE = 1) */
	Spi_SetSSOE(SPI_1);	

    while(1)
    {
    	while(high == Gpio_GetPinStateVal(portc, pin13));

    	delay(150000);

		Spi_PeripheralEnable(SPI_1);	/* Enabling SPI1 Peripheral. */

		/* Send SPI Data, blocking code */
		Spi_SendData(SPI1, (uint8_t*)user_data, strlen(user_data));

		while (1u == Spi_ReadBSYFlag(SPI_1));
	
		Spi_PeripheralDisable(SPI_1);
    }
}

