/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <gpio.h>
#include "sys_f446xx.h"

void delay(void);

uint8_t volatile g_button_pressed = 0;
uint8_t g_button_press_counter = 0;

int main(void)
{
	/* Pin 13 of Port C is connected to On-Board User Button */
	Gpio_PortInit(portc);
	
	/* SysCfg needs to be initialized in order to use EXTI peripheral */
	SysCfg_Init();
	/* Pin 13 of port C is selected as source of triggering for EXTI 
	   interrupt */
	SysCfg_ExtIntCfg(portc, pin13);

	/* Edge detection is set for selected pin */
	EXIT_EdgeDetection(falling, pin13);
	/* Out of the 23 sources of interrupt, pin 13 is enabled */
	EXIT_ISRMaskBitSet(pin13);

	/* We enable EXIT15_10 interrupt in the NVIC peripheral */
	NVIC_EnableIRQ(EXTI15_10_IRQn);

	/* Loop forever */
	while(1)
	{
		/* We check if the button has been pressed */
		if(g_button_pressed)
        {
            delay();
			/* Increment global counter and print it to the console */
            g_button_press_counter++;
            printf("\nButton is pressed %u times!", g_button_press_counter);
            g_button_pressed = 0;
        }
	}
}

/* Delay for debouncing of GPIO Pin */
void delay(void)
{
    for(uint32_t i = 0; i < 200000; i++);
}

/* ISR handler */
void EXTI15_10_IRQHandler(void)
{
	/* Check for the Pending bit on the Pending Register */
    if(high == EXIT_PendISRReadBit(pin13))
    {
        /* Clear pin */
        EXIT_PendISRClearBit(pin13);
    }
	/* We raise the flag that will be fetch in the while loop */
    g_button_pressed = 1;
}
